#+TITLE: OS Keybinds
#+DESCRIPTION: Universal keybinds across OS. Very useful for not fucking up your muscle memory.
A custom function called `get-hotkey-config` is defined in our doom config to get relative filepaths based on string

* Some notes
** TODO figure out a way to acquire relative user config path (for windows bc windows is windows)
  - "~/.skhdrc"
  - "~/.config/i3/config"
  - "uhhhh `shell:startup and put the file in there?"
** TODO i3 config also contains non-keybind settings. probably a good idea to tangle those in as well.
** TODO i3 has a bunch of even more keybinds unique to its situation. need to represent these on here too.

* AHK Setup
#+begin_src ahk
;Define Komorebic command for easier access
Komorebic(cmd) {
    RunWait(format("komorebic.exe {}", cmd), , "Hide")
}
#+end_src

* i3 setup
#+begin_src sh
set $mod Mod4
#For some reason, Mod1 is alt, not "Alt"
set $alt Mod1
#+end_src
* Caps to Control
#+begin_src sh :tangle ~/.xmodmap
remove Lock = Caps_Lock
keysym Caps_Lock = Control_L
add Control = Control_L
#+end_src
* Window Management
** Turn on/off Window Tiling Mode
*** i3
*** skhd
*** ahk
#+begin_src ahk
^+#]::Komorebic("start") ;;explicitly enable ffm for focus_folows_mouse
^+#[::Komorebic("stop") ;;TODO: grab all windows and move them back to the front
#+end_src
** Change Window Focus and Move Mouse
MOD + hjkl
*** i3
Runs our focus script which also moves focus within tmux, nvim, or emacs
#+begin_src sh :tangle "~/.config/i3/config"
bindsym $mod+h exec --no-startup-id ~/.config/i3/bin/focus left
bindsym $mod+j exec --no-startup-id ~/.config/i3/bin/focus down
bindsym $mod+k exec --no-startup-id ~/.config/i3/bin/focus up
bindsym $mod+l exec --no-startup-id ~/.config/i3/bin/focus right
#+end_src
*** skhd
(currently alt + shift + hjkl)
#+begin_src :tangle "~/.skhdrc"
alt + shift - h : yabai -m window --focus west
alt + shift - j : yabai -m window --focus south
alt + shift - k : yabai -m window --focus north
alt + shift - l : yabai -m window --focus east
#+end_src
*** ahk
(currently ctrl + win + hjkl)
#+begin_src ahk
^#h::Komorebic("focus left")
^#j::Komorebic("focus down")
^#k::Komorebic("focus up")
^#l::Komorebic("focus right")
#+end_src
** Swap Window
*** i3
#+begin_src

#+end_src
*** skhd
#+begin_src
alt + shift - o : yabai -m window --swap north
alt + shift - i : yabai -m window --swap south
alt + shift - u : yabai -m window --swap west
alt + shift - p : yabai -m window --swap east
#+end_src
*** ahk
#+begin_src ahk
+#h::Komorebic("move left")
+#j::Komorebic("move down")
+#k::Komorebic("move up")
+#l::Komorebic("move right")
#+end_src
** Resize Window
*** i3
#+begin_src sh
# resize window relative to its position on the display
bindsym $mod+Shift+h exec --no-startup-id ~/.config/i3/bin/resize-relative left 50
bindsym $mod+Shift+l exec --no-startup-id ~/.config/i3/bin/resize-relative right 50
bindsym $mod+Shift+j exec --no-startup-id ~/.config/i3/bin/resize-relative down 50
bindsym $mod+Shift+k exec --no-startup-id ~/.config/i3/bin/resize-relative up 50

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
#+end_src
*** skhd
*** ahk
#+begin_src ahk
^+#h::Komorebic("resize-axis horizontal decrease")
^+#j::Komorebic("resize-axis vertical decrease")
^+#k::Komorebic("resize-axis vertical increase")
^+#l::Komorebic("resize-axis horizontal increase")
#+end_src
** Change Workspace
*** i3
#+begin_src sh
# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

#+end_src
*** skhd
*** ahk
#+begin_src ahk
#1::Komorebic("focus-workspace 0")
#2::Komorebic("focus-workspace 1")
#3::Komorebic("focus-workspace 2")
#4::Komorebic("focus-workspace 3")
#5::Komorebic("focus-workspace 4")
#6::Komorebic("focus-workspace 5")
#7::Komorebic("focus-workspace 6")
#8::Komorebic("focus-workspace 7")
#+end_src
** Throw Window to Workspace
*** i3
#+begin_src sh
# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10
#+end_src
*** skhd
#+begin_src
alt + shift - 1 : yabai -m window --space 1
alt + shift - 2 : yabai -m window --space 2
alt + shift - 3 : yabai -m window --space 3
alt + shift - 4 : yabai -m window --space 4
alt + shift - 5 : yabai -m window --space 5
#+end_src
*** ahk
#+begin_src ahk
#+1::Komorebic("move-to-workspace 0")
#+2::Komorebic("move-to-workspace 1")
#+3::Komorebic("move-to-workspace 2")
#+4::Komorebic("move-to-workspace 3")
#+5::Komorebic("move-to-workspace 4")
#+6::Komorebic("move-to-workspace 5")
#+7::Komorebic("move-to-workspace 6")
#+8::Komorebic("move-to-workspace 7")
#+end_src
** Fullscreen Window
*** i3
#+begin_src sh
# enter fullscreen mode for the focused container
#bindsym $mod+f exec --no-startup-id ~/.config/i3/bin/toggle-fullscreen
bindsym $mod+f fullscreen toggle
#+end_src
*** skhd
#+begin_src
alt + shift - return : yabai -m window --toggle zoom-fullscreen
#+end_src
*** ahk
#+begin_src ahk
#f::Komorebic("toggle-maximize")
#+end_src
** Close Window
*** i3
#+begin_src sh
# Kill window (doesn't kill processes)
# We DONT put xkill because that also kills daemons actually. not good for emacs.
bindsym $mod+Shift+q kill
#+end_src
*** skhd
*** ahk
#+begin_src ahk
#+q::Komorebic("close")
#+end_src
** Toggle Float
*** i3
#+begin_src sh
# Toggle the focused window to either float / tile
# If it's now floating, moves it to the mouse
bindsym $mod+Shift+o [con_id=__focused__] floating toggle, move position mouse
#+end_src
*** skhd
#+begin_src
alt + shift - f : yabai -m window --toggle float
#+end_src
*** ahk
#+begin_src ahk
#o::Komorebic("toggle-float")
#+end_src

* dmenu
** i3
#+begin_src sh
# start dmenu (a program launcher)
#bindsym $mod+d exec --no-startup-id dmenu_run
bindsym $mod+Return exec --no-startup-id rofi -show drun -show-icons
bindsym $mod+Shift+Return exec --no-startup-id rofi -show run
bindsym $mod+Ctrl+Return exec --no-startup-id env NO_TMUX=true alacritty
#+end_src
